services:
  server:
    container_name: listarec
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./work:/penguinpanthers:Z
    command: ["bash", "--rcfile", "/penguinpanthers/.bashrc", "-i"]
